const bike = [
    { name: 'Bombtrack Munroe Cargo - Cargobike - 2021 - matt metallic green', description: 'Allowing it to transport a month’s shopping home, or an entire house party’s worth of refreshments, it’s one more reason not to use a car. Odd wheels for balanced handling. With a strong and manoeuvrable 20-inch front wheel providing strength and a rear 27.5-inch hoop taking care of rider comfort, the Bombtrack Munroe Cargo will look after both you and your stuff.', image: '', price: 4873 },
    { name: 'BMC URS 01 TWO - Force eTap AXS Eagle Gravelbike - 2021 - persian green', description: 'Probably the only bear you’ll ever want to cross paths with. BMC URS likes to roam UnReStricted to nurture its wild side. The super lightweight, race-ready frame and capable build come together with textbook BMC precision, cutting-edge integration and scrupulously developed Gravel+ geometry.', image: '', price: 6768 },
    { name: 'CUBE SL Road SL - Fitnessbike - 2021 - grey/red', description: "The SL Road SL is a featherweight, minimalist speed machine combining the efficiency of a road race bike with the adaptability of a tourer. Commuter, Strava KOM-chaser or weekend adventurer - it's your choice. Shimano's superb Ultegra 2x11 transmission delivers a huge range of gears at the push of a button. Shimano's powerful flat mount hydraulic disc brakes serve up matching stopping power in all weathers. Aero rims add to the sense of purpose. And the full carbon fork ensures you'll be comfortable from the start of your ride to the end. ", image: '', price: 130168 },
    { name: 'CUBE SL Road SL - Fitnessbike - 2021 - grey/red', description: "The SL Road SL is a featherweight, minimalist speed machine combining the efficiency of a road race bike with the adaptability of a tourer. Commuter, Strava KOM-chaser or weekend adventurer - it's your choice. Shimano's superb Ultegra 2x11 transmission delivers a huge range of gears at the push of a button. Shimano's powerful flat mount hydraulic disc brakes serve up matching stopping power in all weathers. Aero rims add to the sense of purpose. And the full carbon fork ensures you'll be comfortable from the start of your ride to the end. ", image: '', price: 130168 },

    {
        name: "Ghost LECTOR FS Essential - 29 Carbon Mountainbike - 2021 - petrol / ocean", description:
            "Developed in cooperation with the Ghost Cross Country Team and the world's toughest trails in mind: The LECTOR FS is a milestone in the evolution of Race full-suspensions! Thanks to the SuperFit geometry, every rider will find the perfectly fitting frame - in full carbon, naturally", image: '', price: 25207
    },

]